{{- if .Values.far.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fence-agents-remediation-controller-manager
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: fence-agents-remediation-operator
    {{- include "kubevirt-stack.labels" . | nindent 4 }}
{{- end }}
