{{- if .Values.snr.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: self-node-remediation-controller-manager
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: self-node-remediation-operator
    control-plane: controller-manager
    {{- include "kubevirt-stack.labels" . | nindent 4 }}
{{- end }}
